receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:

  memory_limiter:
    limit_mib: 512
    check_interval: 1s

  batch:

exporters:

  elasticsearch/logs:
    endpoints:
      - http://elasticsearch:9200

    logs_index: app-logs

  elasticsearch/traces:
    endpoints:
      - http://elasticsearch:9200

    traces_index: app-traces

service:

  pipelines:

    logs:
      receivers:
        - otlp

      processors:
        - memory_limiter
        - batch

      exporters:
        - elasticsearch/logs

    traces:
      receivers:
        - otlp

      processors:
        - memory_limiter
        - batch

      exporters:
        - elasticsearch/traces